# Generated by Django 4.0.2 on 2022-02-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postextras',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
