# Generated by Django 4.0.2 on 2022-02-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0006_people_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Post_image',
        ),
        migrations.AlterField(
            model_name='people',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend1.post')),
            ],
        ),
    ]
