# Generated by Django 4.0.2 on 2022-03-02 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend1', '0008_post_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='people',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
