# Generated by Django 4.0.2 on 2022-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0009_remove_people_email_remove_people_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='people',
            name='Birth_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
