# Generated by Django 4.0.2 on 2022-03-16 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend1', '0013_post_tag1_name_post_tag2_name_post_tag3_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users',
            field=models.ManyToManyField(related_name='users_hidden_from_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
