# Generated by Django 4.0.2 on 2022-03-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0014_post_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
