# Generated by Django 4.0.2 on 2022-03-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0017_people_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='OTP',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
