# Generated by Django 4.0.2 on 2022-03-21 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend1', '0018_people_otp_people_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
