# Generated by Django 4.0.2 on 2022-03-26 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend1', '0019_people_name_alter_people_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=255, null=True)),
                ('GST_number', models.CharField(max_length=255, null=True)),
                ('Company_Address1', models.CharField(max_length=255, null=True)),
                ('Company_Address2', models.CharField(max_length=255, null=True)),
                ('City', models.CharField(max_length=255, null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('pinCode', models.CharField(max_length=255, null=True)),
                ('About', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
