# Generated by Django 4.0.2 on 2022-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0020_validatecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
