# Generated by Django 4.0.2 on 2022-03-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0022_people_step_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='step_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='step_3',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=255, null=True)),
                ('no_of_products', models.IntegerField(null=True)),
                ('no_of_views', models.IntegerField(null=True)),
                ('send_products', models.CharField(max_length=255, null=True)),
                ('send_products_back', models.CharField(max_length=255, null=True)),
                ('product_additional_specifications', models.TextField(null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend1.people')),
            ],
        ),
    ]
