# Generated by Django 4.0.2 on 2022-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0023_people_step_2_people_step_3_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='orderID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
