# Generated by Django 4.0.2 on 2022-03-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0024_product_details_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
