# Generated by Django 4.0.2 on 2022-03-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0025_product_details_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='orderID',
        ),
        migrations.CreateModel(
            name='product_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend1.people')),
            ],
        ),
    ]
