# Generated by Django 4.0.2 on 2022-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0026_remove_product_details_orderid_product_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='completed_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='completed_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='completed_thrice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='completed_twice',
            field=models.BooleanField(default=False),
        ),
    ]
