# Generated by Django 4.0.2 on 2022-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0027_people_completed_four_people_completed_once_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim_free_photos_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('question', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
