# Generated by Django 4.0.2 on 2022-04-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0028_claim_free_photos_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='completed_four',
        ),
        migrations.RemoveField(
            model_name='people',
            name='completed_once',
        ),
        migrations.RemoveField(
            model_name='people',
            name='completed_thrice',
        ),
        migrations.RemoveField(
            model_name='people',
            name='completed_twice',
        ),
        migrations.AddField(
            model_name='people',
            name='stages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
