# Generated by Django 4.0.2 on 2022-04-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0029_remove_people_completed_four_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='stages',
        ),
    ]
