# Generated by Django 4.0.2 on 2022-04-01 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend1', '0031_people_stages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidateCompany',
            new_name='Stage1',
        ),
        migrations.RemoveField(
            model_name='people',
            name='stages',
        ),
    ]
