# Generated by Django 4.0.2 on 2022-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend1', '0035_people_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myName', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
